#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/run-blokus-uct-sweep.sh TRAINING_DIR [CONFIG_FILE]

Environment overrides:
  MODEL                 model path/name/iteration; default: latest checkpoint in TRAINING_DIR/model
  SEARCH_TYPE           model multiplayer search type; default: maxn
  MODEL_SIMS            model actor_num_simulation; default: 50
  BASELINES             baseline list; default: "random greedy greedy_mobility rollout uct_maxn uct_paranoid"
  MCTS_SIMS             pure MCTS sweep list; default: "50 100 200 400"
  ROLLOUTS              flat rollout playouts per move; default: 64
  ROLLOUT_CANDIDATES    flat rollout candidate actions per move; default: 32
  MCTS_LEAF_EVAL        zero or rollout; default: zero
  MCTS_CANDIDATE_LIMIT  pure MCTS candidate actions per node; default: 64
  MCTS_CPUCT            pure MCTS exploration constant; default: 1.0
  GAMES_PER_SEATING     repeated games per generated seating; default: 1
  GAMES                 exact total games; default: 14 * expanded_baseline_count * GAMES_PER_SEATING
  GPU                   GPU list passed to multiplayer-eval.py, e.g. 0123; default: 0123
  NUM_THREADS           arena workers per GPU list expansion; default: 1
  OUTPUT                output directory; default: generated by multiplayer-eval.py
  EXTRA_CONF_STR        extra MiniZero config overrides for model agent
  RESUME_MODE           --resume or --overwrite; default: --resume
  DRY_RUN               1 to only generate arena.json; default: 0

Examples:
  scripts/run-blokus-uct-sweep.sh blokus_maxn_smoke_01

  GAMES_PER_SEATING=5 GPU=0123 MODEL=55500 \
    scripts/run-blokus-uct-sweep.sh blokus_maxn_smoke_01

  BASELINES="uct_maxn uct_paranoid" MCTS_SIMS="50 100" GPU=0 MODEL=55500 \
    scripts/run-blokus-uct-sweep.sh blokus_maxn_smoke_01

Outputs:
  arena.json
  games.jsonl
  agent_summary.csv / agent_summary.png
  seat_summary.csv / seat_summary.png
  seating_summary.csv
  mcts_sweep_summary.csv / mcts_sweep.png
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

training_dir="${1:-blokus_maxn_smoke_01}"
if [[ ! -d "${training_dir}" ]]; then
  echo "training directory not found: ${training_dir}" >&2
  usage >&2
  exit 1
fi

if [[ $# -ge 2 ]]; then
  conf_file="$2"
else
  run_name="$(basename "${training_dir}")"
  if [[ -f "${training_dir}/${run_name}.cfg" ]]; then
    conf_file="${training_dir}/${run_name}.cfg"
  else
    conf_file=""
  fi
fi

search_type="${SEARCH_TYPE:-maxn}"
model_sims="${MODEL_SIMS:-50}"
mcts_sims="${MCTS_SIMS:-50 100 200 400}"
baselines="${BASELINES:-random greedy greedy_mobility rollout uct_maxn uct_paranoid}"
rollouts="${ROLLOUTS:-64}"
rollout_candidates="${ROLLOUT_CANDIDATES:-32}"
mcts_leaf_eval="${MCTS_LEAF_EVAL:-zero}"
mcts_candidate_limit="${MCTS_CANDIDATE_LIMIT:-64}"
mcts_cpuct="${MCTS_CPUCT:-1.0}"
games_per_seating="${GAMES_PER_SEATING:-1}"
gpu="${GPU:-0123}"
num_threads="${NUM_THREADS:-1}"
resume_mode="${RESUME_MODE:---resume}"
dry_run="${DRY_RUN:-0}"

read -r -a mcts_sims_array <<< "${mcts_sims}"
if [[ "${#mcts_sims_array[@]}" -eq 0 ]]; then
  echo "MCTS_SIMS must contain at least one positive integer" >&2
  exit 1
fi
read -r -a baselines_array <<< "${baselines}"
if [[ "${#baselines_array[@]}" -eq 0 ]]; then
  echo "BASELINES must contain at least one baseline" >&2
  exit 1
fi

expanded_baseline_count=0
for baseline in "${baselines_array[@]}"; do
  if [[ "${baseline}" == "uct_maxn" || "${baseline}" == "uct_paranoid" ]]; then
    expanded_baseline_count=$((expanded_baseline_count + ${#mcts_sims_array[@]}))
  else
    expanded_baseline_count=$((expanded_baseline_count + 1))
  fi
done

default_games=$((14 * expanded_baseline_count * games_per_seating))
games="${GAMES:-${default_games}}"

cmd=(
  python3 tools/multiplayer-eval.py blokus-baseline "${training_dir}"
  --search-type "${search_type}"
  --num-simulations "${model_sims}"
  --baselines "${baselines_array[@]}"
  --rollouts "${rollouts}"
  --candidate-limit "${rollout_candidates}"
  --mcts-simulations "${mcts_sims_array[@]}"
  --mcts-leaf-eval "${mcts_leaf_eval}"
  --mcts-candidate-limit "${mcts_candidate_limit}"
  --mcts-cpuct "${mcts_cpuct}"
  --games "${games}"
  -g "${gpu}"
  --num_threads "${num_threads}"
  "${resume_mode}"
)

if [[ -n "${conf_file}" ]]; then
  cmd+=(--conf-file "${conf_file}")
fi
if [[ -n "${MODEL:-}" ]]; then
  cmd+=(--model "${MODEL}")
fi
if [[ -n "${OUTPUT:-}" ]]; then
  cmd+=(--output "${OUTPUT}")
fi
if [[ -n "${EXTRA_CONF_STR:-}" ]]; then
  cmd+=(-conf_str "${EXTRA_CONF_STR}")
fi
if [[ "${dry_run}" == "1" || "${dry_run}" == "true" ]]; then
  cmd+=(--dry-run)
fi

echo "Blokus baseline sweep"
echo "  training_dir=${training_dir}"
echo "  conf_file=${conf_file:-auto}"
echo "  model=${MODEL:-latest}"
echo "  model_search_type=${search_type}"
echo "  model_sims=${model_sims}"
echo "  baselines=${baselines}"
echo "  expanded_baseline_count=${expanded_baseline_count}"
echo "  rollout_playouts=${rollouts}"
echo "  rollout_candidate_limit=${rollout_candidates}"
echo "  pure_mcts_sims=${mcts_sims}"
echo "  mcts_leaf_eval=${mcts_leaf_eval}"
echo "  mcts_candidate_limit=${mcts_candidate_limit}"
echo "  games=${games} (${games_per_seating} per seating if using default)"
echo "  gpu=${gpu}"
echo "  num_threads=${num_threads}"
echo "  dry_run=${dry_run}"
echo
printf 'Command:'
printf ' %q' "${cmd[@]}"
printf '\n\n'

"${cmd[@]}"
