#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# Performance-oriented, from-scratch JPSRO-guided Blokus10 run. This keeps
# most data on-policy while using JPSRO to select hard frozen joint profiles.
export GUIDED_TOTAL_ITERATIONS="${GUIDED_TOTAL_ITERATIONS:-300}"
export GUIDED_BOOTSTRAP_ITERATIONS="${GUIDED_BOOTSTRAP_ITERATIONS:-25}"
export GUIDED_META_INTERVAL="${GUIDED_META_INTERVAL:-25}"
export GUIDED_CURRENT_RATIO="${GUIDED_CURRENT_RATIO:-0.50}"
export GUIDED_HARD_RATIO="${GUIDED_HARD_RATIO:-0.15}"
export GUIDED_CCE_RATIO="${GUIDED_CCE_RATIO:-0.05}"
export GUIDED_HISTORY_RATIO="${GUIDED_HISTORY_RATIO:-0.30}"
export GUIDED_POPULATION_SIZE="${GUIDED_POPULATION_SIZE:-8}"
export GUIDED_HARD_TEMPERATURE="${GUIDED_HARD_TEMPERATURE:-0.35}"
export GUIDED_HARD_CONFIDENCE="${GUIDED_HARD_CONFIDENCE:-1.0}"
export GUIDED_GENERALIST_ADMISSION="${GUIDED_GENERALIST_ADMISSION:-true}"
export GUIDED_MAX_SEAT_REGRESSION="${GUIDED_MAX_SEAT_REGRESSION:-0.05}"
export GUIDED_ADMISSION_GAIN="${GUIDED_ADMISSION_GAIN:-0.005}"
export GUIDED_ADMISSION_CONFIDENCE="${GUIDED_ADMISSION_CONFIDENCE:-1.5}"
export GUIDED_EVAL_GAMES="${GUIDED_EVAL_GAMES:-20}"
export GUIDED_DEVIATION_GAMES="${GUIDED_DEVIATION_GAMES:-100}"
export GUIDED_RANK_UTILITY_WEIGHT="${GUIDED_RANK_UTILITY_WEIGHT:-0.25}"
export GUIDED_SIMULATIONS="${GUIDED_SIMULATIONS:-50}"
export GUIDED_SEED="${GUIDED_SEED:-0}"

run_dir="${1:-runs/blokus10_jpsro_strong_300_s0}"
exec tools/train-blokus10-jpsro-rank-300.sh "$run_dir"
